import { Container } from '@/styled-system/jsx'
import '@/theme/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from './_components/footer'
import Header from './_components/header'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className="dark">
			<body className={inter.className}>
				<Container maxW="6xl" height="100%" display="flex" flexDir="column">
					<Header />
					{children}
					<Footer />
				</Container>
			</body>
		</html>
	)
}
